version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: points-backend
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
    networks:
      - points-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: points-frontend
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - points-network

networks:
  points-network:
    driver: bridge
